
import type { ReactNode } from 'react';
import type { Timestamp } from 'firebase/firestore';

export type PerceptionKeys = "neutral" | "fan" | "simp" | "hater";

export interface PerceptionOption {
  key: PerceptionKeys;
  label: string;
  icon: React.ElementType;
}

export type EmotionKey = 'alegria' | 'envidia' | 'tristeza' | 'miedo' | 'desagrado' | 'furia';
export type AttitudeKey = 'neutral' | 'fan' | 'simp' | 'hater';
export type StarValue = 1 | 2 | 3 | 4 | 5;
export type StarValueAsString = "1" | "2" | "3" | "4" | "5";

export interface FamilyMember {
  id: string; // Unique ID for this entry in the array (e.g., generated by nanoid or similar)
  name: string;
  relationship: string; // e.g., "Padre", "Madre", "Abuelo paterno", "Hermana", "Hijo/a"
  figureId?: string | null; // Optional: ID of the figure if they exist as a separate profile
  photoUrl?: string | null; // Optional: Direct URL to a photo for this family member
}

export interface Figure {
  id: string;
  name: string;
  nameLower: string;
  photoUrl: string;
  description?: string;
  
  nationality?: string;
  occupation?: string;
  gender?: string;

  species?: string; 
  firstAppearance?: string; 
  birthDateOrAge?: string; 
  birthPlace?: string;
  maritalStatus?: string; 
  
  height?: string;
  weight?: string; 
  hairColor?: string;

  perceptionCounts?: Record<EmotionKey, number>;
  attitudeCounts?: Record<AttitudeKey, number>;
  starRatingCounts?: Record<StarValueAsString, number>;
  commentCount?: number; 
  familyMembers?: FamilyMember[]; // Array to store family members
  createdAt?: string; 
  status?: 'approved' | 'rejected'; 
}

export interface UserPerception {
  userId: string;
  figureId: string;
  emotion: EmotionKey;
  timestamp: Timestamp; 
}

export interface UserAttitude {
  userId: string;
  figureId: string;
  attitude: AttitudeKey;
  timestamp: Timestamp; 
}

export interface UserStarRating {
  userId: string;
  figureId: string;
  starValue: StarValue; 
  timestamp: Timestamp; 
}

export interface UserComment {
  id: string; 
  figureId: string;
  userId: string;
  username: string; 
  userPhotoURL: string | null; 
  text: string;
  starRatingGiven: StarValue | null; 
  createdAt: Timestamp; 
  updatedAt?: Timestamp | null;
  likes: number;
  dislikes: number;
  likedBy: string[]; 
  dislikedBy: string[]; 
}


export interface Country {
  name: string;
  code: string;
  emoji: string;
}

export interface UserProfile {
  uid: string;
  email: string | null;
  username: string;
  country?: string;
  countryCode?: string;
  gender?: string; 
  photoURL?: string | null;
  role: 'user' | 'admin';
  createdAt: string; 
  lastLoginAt?: string; 
}

export interface GalleryImage {
  id: string;
  imageUrl: string;
  userId: string;
  username?: string;
  createdAt: Timestamp;
}
