
/* eslint-disable no-undef */
// This file is used to extend the service worker generated by next-pwa.
// It allows us to import and use other scripts, like the Firebase messaging service worker.

// self: a reference to the service worker itself.
// __WB_MANIFEST: a variable injected by Workbox (used by next-pwa) that contains the list of assets to precache.
// If you want to customize precaching, you can manipulate this variable.
workbox.precaching.precacheAndRoute(self.__WB_MANIFEST || []);


// The importScripts call is now safely handled here, ensuring it doesn't
// conflict with Next.js's own chunk loading and resolving the ChunkLoadError.
try {
    importScripts('/firebase-messaging-sw.js');
    console.log("Successfully imported Firebase messaging service worker.");
} catch (e) {
    console.error("Failed to import Firebase messaging service worker:", e);
}
