
// This file is a copy of the main app's countries config
// to ensure the functions directory is self-contained.

import type { Country } from './types';

export const COUNTRIES: Country[] = [
  { name: 'Afganistán', code: 'AF', emoji: '🇦🇫' },
  { name: 'Albania', code: 'AL', emoji: '🇦🇱' },
  { name: 'Alemania', code: 'DE', emoji: '🇩🇪' },
  { name: 'Andorra', code: 'AD', emoji: '🇦🇩' },
  { name: 'Angola', code: 'AO', emoji: '🇦🇴' },
  { name: 'Antigua y Barbuda', code: 'AG', emoji: '🇦🇬' },
  { name: 'Arabia Saudita', code: 'SA', emoji: '🇸🇦' },
  { name: 'Argelia', code: 'DZ', emoji: '🇩🇿' },
  { name: 'Argentina', code: 'AR', emoji: '🇦🇷' },
  { name: 'Armenia', code: 'AM', emoji: '🇦🇲' },
  { name: 'Australia', code: 'AU', emoji: '🇦🇺' },
  { name: 'Austria', code: 'AT', emoji: '🇦🇹' },
  { name: 'Azerbaiyán', code: 'AZ', emoji: '🇦🇿' },
  { name: 'Bahamas', code: 'BS', emoji: '🇧🇸' },
  { name: 'Bangladés', code: 'BD', emoji: '🇧🇩' },
  { name: 'Barbados', code: 'BB', emoji: '🇧🇧' },
  { name: 'Baréin', code: 'BH', emoji: '🇧🇭' },
  { name: 'Bélgica', code: 'BE', emoji: '🇧🇪' },
  { name: 'Belice', code: 'BZ', emoji: '🇧🇿' },
  { name: 'Benín', code: 'BJ', emoji: '🇧🇯' },
  { name: 'Bielorrusia', code: 'BY', emoji: '🇧🇾' },
  { name: 'Bolivia', code: 'BO', emoji: '🇧🇴' },
  { name: 'Bosnia y Herzegovina', code: 'BA', emoji: '🇧🇦' },
  { name: 'Botsuana', code: 'BW', emoji: '🇧🇼' },
  { name: 'Brasil', code: 'BR', emoji: '🇧🇷' },
  { name: 'Brunéi', code: 'BN', emoji: '🇧🇳' },
  { name: 'Bulgaria', code: 'BG', emoji: '🇧🇬' },
  { name: 'Burkina Faso', code: 'BF', emoji: '🇧🇫' },
  { name: 'Burundi', code: 'BI', emoji: '🇧🇮' },
  { name: 'Bután', code: 'BT', emoji: '🇧🇹' },
  { name: 'Cabo Verde', code: 'CV', emoji: '🇨🇻' },
  { name: 'Camboya', code: 'KH', emoji: '🇰🇭' },
  { name: 'Camerún', code: 'CM', emoji: '🇨🇲' },
  { name: 'Canadá', code: 'CA', emoji: '🇨🇦' },
  { name: 'Catar', code: 'QA', emoji: '🇶🇦' },
  { name: 'Chad', code: 'TD', emoji: '🇹🇩' },
  { name: 'Chile', code: 'CL', emoji: '🇨🇱' },
  { name: 'China', code: 'CN', emoji: '🇨🇳' },
  { name: 'Chipre', code: 'CY', emoji: '🇨🇾' },
  { name: 'Colombia', code: 'CO', emoji: '🇨🇴' },
  { name: 'Comoras', code: 'KM', emoji: '🇰🇲' },
  { name: 'Corea del Norte', code: 'KP', emoji: '🇰🇵' },
  { name: 'Corea del Sur', code: 'KR', emoji: '🇰🇷' },
  { name: 'Costa de Marfil', code: 'CI', emoji: '🇨🇮' },
  { name: 'Costa Rica', code: 'CR', emoji: '🇨🇷' },
  { name: 'Croacia', code: 'HR', emoji: '🇭🇷' },
  { name: 'Cuba', code: 'CU', emoji: '🇨🇺' },
  { name: 'Dinamarca', code: 'DK', emoji: '🇩🇰' },
  { name: 'Dominica', code: 'DM', emoji: '🇩🇲' },
  { name: 'Ecuador', code: 'EC', emoji: '🇪🇨' },
  { name: 'Egipto', code: 'EG', emoji: '🇪🇬' },
  { name: 'El Salvador', code: 'SV', emoji: '🇸🇻' },
  { name: 'Emiratos Árabes Unidos', code: 'AE', emoji: '🇦🇪' },
  { name: 'Eritrea', code: 'ER', emoji: '🇪🇷' },
  { name: 'Eslovaquia', code: 'SK', emoji: '🇸🇰' },
  { name: 'Eslovenia', code: 'SI', emoji: '🇸🇮' },
  { name: 'España', code: 'ES', emoji: '🇪🇸' },
  { name: 'Estados Unidos', code: 'US', emoji: '🇺🇸' },
  { name: 'Estonia', code: 'EE', emoji: '🇪🇪' },
  { name: 'Etiopía', code: 'ET', emoji: '🇪🇹' },
  { name: 'Filipinas', code: 'PH', emoji: '🇵🇭' },
  { name: 'Finlandia', code: 'FI', emoji: '🇫🇮' },
  { name: 'Fiyi', code: 'FJ', emoji: '🇫🇯' },
  { name: 'Francia', code: 'FR', emoji: '🇫🇷' },
  { name: 'Gabón', code: 'GA', emoji: '🇬🇦' },
  { name: 'Gambia', code: 'GM', emoji: '🇬🇲' },
  { name: 'Georgia', code: 'GE', emoji: '🇬🇪' },
  { name: 'Ghana', code: 'GH', emoji: '🇬🇭' },
  { name: 'Granada', code: 'GD', emoji: '🇬🇩' },
  { name: 'Grecia', code: 'GR', emoji: '🇬🇷' },
  { name: 'Guatemala', code: 'GT', emoji: '🇬🇹' },
  { name: 'Guinea', code: 'GN', emoji: '🇬🇳' },
  { name: 'Guinea-Bisáu', code: 'GW', emoji: '🇬🇼' },
  { name: 'Guinea Ecuatorial', code: 'GQ', emoji: '🇬🇶' },
  { name: 'Guyana', code: 'GY', emoji: '🇬🇾' },
  { name: 'Haití', code: 'HT', emoji: '🇭🇹' },
  { name: 'Honduras', code: 'HN', emoji: '🇭🇳' },
  { name: 'Hungría', code: 'HU', emoji: '🇭🇺' },
  { name: 'India', code: 'IN', emoji: '🇮🇳' },
  { name: 'Indonesia', code: 'ID', emoji: '🇮🇩' },
  { name: 'Irak', code: 'IQ', emoji: '🇮🇶' },
  { name: 'Irán', code: 'IR', emoji: '🇮🇷' },
  { name: 'Irlanda', code: 'IE', emoji: '🇮🇪' },
  { name: 'Islandia', code: 'IS', emoji: '🇮🇸' },
  { name: 'Islas Marshall', code: 'MH', emoji: '🇲🇭' },
  { name: 'Islas Salomón', code: 'SB', emoji: '🇸🇧' },
  { name: 'Israel', code: 'IL', emoji: '🇮🇱' },
  { name: 'Italia', code: 'IT', emoji: '🇮🇹' },
  { name: 'Jamaica', code: 'JM', emoji: '🇯🇲' },
  { name: 'Japón', code: 'JP', emoji: '🇯🇵' },
  { name: 'Jordania', code: 'JO', emoji: '🇯🇴' },
  { name: 'Kazajistán', code: 'KZ', emoji: '🇰🇿' },
  { name: 'Kenia', code: 'KE', emoji: '🇰🇪' },
  { name: 'Kirguistán', code: 'KG', emoji: '🇰🇬' },
  { name: 'Kiribati', code: 'KI', emoji: '🇰🇮' },
  { name: 'Kuwait', code: 'KW', emoji: '🇰🇼' },
  { name: 'Laos', code: 'LA', emoji: '🇱🇦' },
  { name: 'Lesoto', code: 'LS', emoji: '🇱🇸' },
  { name: 'Letonia', code: 'LV', emoji: '🇱🇻' },
  { name: 'Líbano', code: 'LB', emoji: '🇱🇧' },
  { name: 'Liberia', code: 'LR', emoji: '🇱🇷' },
  { name: 'Libia', code: 'LY', emoji: '🇱🇾' },
  { name: 'Liechtenstein', code: 'LI', emoji: '🇱🇮' },
  { name: 'Lituania', code: 'LT', emoji: '🇱🇹' },
  { name: 'Luxemburgo', code: 'LU', emoji: '🇱🇺' },
  { name: 'Macedonia del Norte', code: 'MK', emoji: '🇲🇰' },
  { name: 'Madagascar', code: 'MG', emoji: '🇲🇬' },
  { name: 'Malasia', code: 'MY', emoji: '🇲🇾' },
  { name: 'Malaui', code: 'MW', emoji: '🇲🇼' },
  { name: 'Maldivas', code: 'MV', emoji: '🇲🇻' },
  { name: 'Malí', code: 'ML', emoji: '🇲🇱' },
  { name: 'Malta', code: 'MT', emoji: '🇲🇹' },
  { name: 'Marruecos', code: 'MA', emoji: '🇲🇦' },
  { name: 'Mauricio', code: 'MU', emoji: '🇲🇺' },
  { name: 'Mauritania', code: 'MR', emoji: '🇲🇷' },
  { name: 'México', code: 'MX', emoji: '🇲🇽' },
  { name: 'Micronesia', code: 'FM', emoji: '🇫🇲' },
  { name: 'Moldavia', code: 'MD', emoji: '🇲🇩' },
  { name: 'Mónaco', code: 'MC', emoji: '🇲🇨' },
  { name: 'Mongolia', code: 'MN', emoji: '🇲🇳' },
  { name: 'Montenegro', code: 'ME', emoji: '🇲🇪' },
  { name:_version: '2',
    name: 'Mozambique', code: 'MZ', emoji: '🇲🇿' },
  { name: 'Myanmar (Birmania)', code: 'MM', emoji: '🇲🇲' },
  { name: 'Namibia', code: 'NA', emoji: '🇳🇦' },
  { name: 'Nauru', code: 'NR', emoji: '🇳🇷' },
  { name: 'Nepal', code: 'NP', emoji: '🇳🇵' },
  { name: 'Nicaragua', code: 'NI', emoji: '🇳🇮' },
  { name: 'Níger', code: 'NE', emoji: '🇳🇪' },
  { name: 'Nigeria', code: 'NG', emoji: '🇳🇬' },
  { name: 'Noruega', code: 'NO', emoji: '🇳🇴' },
  { name: 'Nueva Zelanda', code: 'NZ', emoji: '🇳🇿' },
  { name: 'Omán', code: 'OM', emoji: '🇴🇲' },
  { name: 'Países Bajos', code: 'NL', emoji: '🇳🇱' },
  { name: 'Pakistán', code: 'PK', emoji: '🇵🇰' },
  { name: 'Palaos', code: 'PW', emoji: '🇵🇼' },
  { name: 'Panamá', code: 'PA', emoji: '🇵🇦' },
  { name: 'Papúa Nueva Guinea', code: 'PG', emoji: '🇵🇬' },
  { name: 'Paraguay', code: 'PY', emoji: '🇵🇾' },
  { name: 'Perú', code: 'PE', emoji: '🇵🇪' },
  { name: 'Polonia', code: 'PL', emoji: '🇵🇱' },
  { name: 'Portugal', code: 'PT', emoji: '🇵🇹' },
  { name: 'Reino Unido', code: 'GB', emoji: '🇬🇧' },
  { name: 'República Centroafricana', code: 'CF', emoji: '🇨🇫' },
  { name: 'República Checa', code: 'CZ', emoji: '🇨🇿' },
  { name: 'República del Congo', code: 'CG', emoji: '🇨🇬' },
  { name: 'República Democrática del Congo', code: 'CD', emoji: '🇨🇩' },
  { name: 'República Dominicana', code: 'DO', emoji: '🇩🇴' },
  { name: 'Ruanda', code: 'RW', emoji: '🇷🇼' },
  { name: 'Rumania', code: 'RO', emoji: '🇷🇴' },
  { name: 'Rusia', code: 'RU', emoji: '🇷🇺' },
  { name: 'Samoa', code: 'WS', emoji: '🇼🇸' },
  { name: 'San Cristóbal y Nieves', code: 'KN', emoji: '🇰🇳' },
  { name: 'San Marino', code: 'SM', emoji: '🇸🇲' },
  { name: 'San Vicente y las Granadinas', code: 'VC', emoji: '🇻🇨' },
  { name: 'Santa Lucía', code: 'LC', emoji: '🇱🇨' },
  { name: 'Santo Tomé y Príncipe', code: 'ST', emoji: '🇸🇹' },
  { name: 'Senegal', code: 'SN', emoji: '🇸🇳' },
  { name: 'Serbia', code: 'RS', emoji: '🇷🇸' },
  { name: 'Seychelles', code: 'SC', emoji: '🇸🇨' },
  { name: 'Sierra Leona', code: 'SL', emoji: '🇸🇱' },
  { name: 'Singapur', code: 'SG', emoji: '🇸🇬' },
  { name: 'Siria', code: 'SY', emoji: '🇸🇾' },
  { name: 'Somalia', code: 'SO', emoji: '🇸🇴' },
  { name: 'Sri Lanka', code: 'LK', emoji: '🇱🇰' },
  { name: 'Suazilandia', code: 'SZ', emoji: '🇸🇿' },
  { name: 'Sudáfrica', code: 'ZA', emoji: '🇿🇦' },
  { name: 'Sudán', code: 'SD', emoji: '🇸🇩' },
  { name: 'Sudán del Sur', code: 'SS', emoji: '🇸🇸' },
  { name: 'Suecia', code: 'SE', emoji: '🇸🇪' },
  { name: 'Suiza', code: 'CH', emoji: '🇨🇭' },
  { name: 'Surinam', code: 'SR', emoji: '🇸🇷' },
  { name: 'Tailandia', code: 'TH', emoji: '🇹🇭' },
  { name: 'Tanzania', code: 'TZ', emoji: '🇹🇿' },
  { name: 'Tayikistán', code: 'TJ', emoji: '🇹🇯' },
  { name: 'Timor Oriental', code: 'TL', emoji: '🇹🇱' },
  { name: 'Togo', code: 'TG', emoji: '🇹🇬' },
  { name: 'Tonga', code: 'TO', emoji: '🇹🇴' },
  { name: 'Trinidad y Tobago', code: 'TT', emoji: '🇹🇹' },
  { name: 'Túnez', code: 'TN', emoji: '🇹🇳' },
  { name: 'Turkmenistán', code: 'TM', emoji: '🇹🇲' },
  { name: 'Turquía', code: 'TR', emoji: '🇹🇷' },
  { name: 'Tuvalu', code: 'TV', emoji: '🇹🇻' },
  { name: 'Ucrania', code: 'UA', emoji: '🇺🇦' },
  { name: 'Uganda', code: 'UG', emoji: '🇺🇬' },
  { name: 'Uruguay', code: 'UY', emoji: '🇺🇾' },
  { name: 'Uzbekistán', code: 'UZ', emoji: '🇺🇿' },
  { name: 'Vanuatu', code: 'VU', emoji: '🇻🇺' },
  { name: 'Venezuela', code: 'VE', emoji: '🇻🇪' },
  { name: 'Vietnam', code: 'VN', emoji: '🇻🇳' },
  { name: 'Yemen', code: 'YE', emoji: '🇾🇪' },
  { name: 'Yibuti', code: 'DJ', emoji: '🇩🇯' },
  { name: 'Zambia', code: 'ZM', emoji: '🇿🇲' },
  { name: 'Zimbabue', code: 'ZW', emoji: '🇿🇼' },
].sort((a, b) => a.name.localeCompare(b.name));
