
export const OCCUPATION_OPTIONS: { value: string; label: string }[] = [
    'Actor',
    'Actor de Doblaje',
    'Actor porno',
    'Actriz',
    'Actriz de Doblaje',
    'Actriz porno',
    'Activista',
    'Alcalde',
    'Alcaldesa',
    'Artista',
    'Astronauta',
    'Autor',
    'Bailarín',
    'Bailarina',
    'Cantante',
    'Chef',
    'Científico',
    'Comediante',
    'Creador de Contenido',
    'Dictador',
    'Diplomático',
    'Director',
    'Director de cine',
    'Diseñador',
    'Diseñador de moda',
    'Diseñador de Vestuario',
    'DJ',
    'Duque',
    'Duquesa',
    'Embajador',
    'Emperador',
    'Emperatriz',
    'Empresario',
    'Escritor',
    'Estudiante',
    'Explorador',
    'Filántropo',
    'Filósofo',
    'Gamer',
    'Gobernador',
    'Guionista',
    'Humorista',
    'Influencer',
    'Inventor',
    'Investigador',
    'Militar',
    'Modelo',
    'Monarca',
    'Músico',
    'Novelista',
    'Periodista',
    'Político',
    'Presentador',
    'Presidente',
    'Primer ministro',
    'Princesa',
    'Príncipe',
    'Productor',
    'Profesor',
    'Programador',
    'Reina',
    'Reportero',
    'Rey',
    'Senador',
    'Streamer',
    'Tecnólogo',
    'TikToker',
    'Villano',
    'Youtuber',
].map(o => ({ value: o, label: o })).sort((a, b) => a.label.localeCompare(b.label));
