
export const TAG_OPTIONS: string[] = [
    'Actor',
    'Actor de Doblaje',
    'Actor porno',
    'Actriz',
    'Actriz de Doblaje',
    'Actriz porno',
    'Activista',
    'Ajedrez',
    'Alcalde',
    'Alcaldesa',
    'Ambient',
    'Anfitrión',
    'Anime',
    'Art pop',
    'Artes marciales mixtas (MMA)',
    'Artista',
    'Astronauta',
    'Atletismo',
    'Automovilismo',
    'Autor',
    'Bachata',
    'Bádminton',
    'Bailarín',
    'Bailarina',
    'Baloncesto',
    'Balonmano',
    'Balonmano playa',
    'Banda',
    'Bandy',
    'Béisbol',
    'Béisbol de campo',
    'Biatlón',
    'Billar',
    'Blues',
    'Blues rock',
    'Bobsleigh',
    'Bolero',
    'Bolos',
    'Bossa nova',
    'Boxeo',
    'Bridge',
    'Bubblegum pop',
    'Buceo',
    'Bungee jumping',
    'Candombe',
    'Canotaje',
    'Cantante',
    'Capoeira',
    'Carreras de autos',
    'Casual',
    'Chef',
    'Cheerleading',
    'Chillwave',
    'Ciencia Ficción',
    'Científico',
    'Ciclismo',
    'Cine',
    'Comediante',
    'Coros',
    'Country',
    'Creador de Contenido',
    'Cricket',
    'Croquet',
    'Crunk',
    'Cumbia',
    'Curling',
    'Dancehall',
    'Deportes',
    'Deportes de Pelota',
    'Dictador',
    'Diplomático',
    'Director',
    'Director de cine',
    'Disco',
    'Diseñador',
    'Diseñador de moda',
    'Diseñador de Vestuario',
    'DJ',
    'Dominó',
    'Drifting',
    'Drum and bass',
    'Dubstep',
    'Duque',
    'Duquesa',
    'E-sports',
    'EDM (Electronic Dance Music)',
    'Electropop',
    'Embajador',
    'Emperador',
    'Empresario',
    'Enduro',
    'Equitación',
    'Escalada',
    'Escalada en roca',
    'Escritor',
    'Esgrima',
    'Esquí acuático',
    'Esquí alpino',
    'Esquí de fondo',
    'Estrategia',
    'Estudiante',
    'Experimental',
    'Explorador',
    'Fantasía',
    'Filántropo',
    'Filósofo',
    'Flamenco',
    'Floorball',
    'Folk',
    'Folk metal',
    'Fórmula 1',
    'Frontón',
    'Fútbol',
    'Fútbol americano',
    'Fútbol sala',
    'Funk',
    'Funk carioca',
    'Gamer',
    'Gangsta rap',
    'Gimnasia',
    'Gimnasia artística',
    'Gimnasia rítmica',
    'Glam metal',
    'Glitch',
    'Go',
    'Gobernador',
    'Golf',
    'Gospel',
    'Grunge',
    'Guionista',
    'Halterofilia',
    'Hard rock',
    'Heavy metal',
    'Hípica',
    'Hip Hop',
    'Hip hop de la Costa Este',
    'Hip hop de la Costa Oeste',
    'Histórico',
    'Hockey sobre césped',
    'Hockey sobre hielo',
    'House',
    'Humorista',
    'Industrial',
    'Influencer',
    'Inventor',
    'Investigador',
    'J-Pop',
    'Jazz',
    'Jiu-jitsu',
    'Judo',
    'K-Pop',
    'Karate',
    'Karting',
    'Kayak',
    'Kendo',
    'Kickboxing',
    'Kin-Ball',
    'Lacrosse',
    'Latin pop',
    'Líder de opinión',
    'Líder Mundial',
    'Lucha libre',
    'Luge',
    'Manga',
    'Marcha atlética',
    'Marcha nórdica',
    'Merengue',
    'Militar',
    'Modelo',
    'Monarca',
    'Motociclismo',
    'Motocross',
    'MotoGP',
    'Mumble rap',
    'Música barroca',
    'Música Clásica',
    'Música de cámara',
    'Música para niños',
    'Música regional mexicana',
    'Música tradicional celta',
    'Música tradicional japonesa',
    'Músico',
    'Natación',
    'Natación en aguas abiertas',
    'Natación sincronizada',
    'Netball',
    'New Age',
    'New Wave',
    'Novelista',
    'Ópera',
    'Pádel',
    'Padel surfing',
    'Paracaidismo',
    'Parapente',
    'Parkour',
    'Patinaje',
    'Patinaje en línea',
    'Patinaje sobre hielo',
    'Pelota vasca',
    'Pentatlón moderno',
    'Periodista',
    'Pilates',
    'Piragüismo',
    'Político',
    'Polo',
    'Polo a caballo',
    'Pop',
    'Pop punk',
    'Pop rock',
    'Post-punk',
    'Presentador',
    'Presidente',
    'Primer ministro',
    'Princesa',
    'Príncipe',
    'Productor',
    'Profesor',
    'Programador',
    'Punk rock',
    'R&B (Rhythm and Blues)',
    'Rafting',
    'Rally',
    'Rap',
    'Rap consciente',
    'Raquetbol',
    'Reggae',
    'Reggaeton',
    'Reina',
    'Remo',
    'Reportero',
    'Rey',
    'Rock',
    'Rock alternativo',
    'Rock and Roll',
    'Rock progresivo',
    'Rugby',
    'Salsa',
    'Salto de esquí',
    'Samba',
    'Sanda',
    'Senador',
    'Senderismo',
    'Serie de TV',
    'Shoegaze',
    'Ska',
    'Skateboarding',
    'Skeleton',
    'Slackline',
    'Snowboarding',
    'Sófbol',
    'Soul',
    'Squash',
    'Streamer',
    'Sumo',
    'Superhéroe',
    'Surf',
    'Synth-pop',
    'Synthwave',
    'Taekwondo',
    'Tango',
    'Techno',
    'Tecnólogo',
    'Teen pop',
    'Tenis',
    'Tenis de mesa',
    'Terror',
    'Thrash metal',
    'TikToker',
    'Tiro con arco',
    'Tiro deportivo',
    'Trance',
    'Trap',
    'Triatlón',
    'Ultimate frisbee',
    'Vela',
    'Villano',
    'Voleibol',
    'Voleibol de playa',
    'Waterpolo',
    'Windsurf',
    'World music',
    'Wushu',
    'Yoga',
    'Youtuber',
].sort((a, b) => a.localeCompare(b));
