
export const TAG_OPTIONS: string[] = [
    'Actor',
    'Actriz',
    'Activista',
    'Anime',
    'Artista',
    'Atleta',
    'Autor',
    'Banda',
    'Cantante',
    'Chef',
    'Ciencia Ficción',
    'Científico',
    'Cine',
    'Comediante',
    'Deportes',
    'Director',
    'Diseñador',
    'DJ',
    'Empresario',
    'Escritor',
    'Fantasía',
    'Filántropo',
    'Filósofo',
    'Gamer',
    'Histórico',
    'Influencer',
    'Inventor',
    'J-Pop',
    'K-Pop',
    'Líder Mundial',
    'Manga',
    'Militar',
    'Modelo',
    'Monarca',
    'Músico',
    'Periodista',
    'Político',
    'Productor',
    'Programador',
    'Reggaetón',
    'Rock',
    'Serie de TV',
    'Superhéroe',
    'Tecnología',
    'Videojuegos',
    'Villano',
    'YouTuber',
].sort((a, b) => a.localeCompare(b));
