
export const TAG_OPTIONS: string[] = [
    'Actor',
    'Actor de Doblaje',
    'Actor porno',
    'Actriz',
    'Actriz de Doblaje',
    'Actriz porno',
    'Activista',
    'Afganistán',
    'Ajedrez',
    'Albania',
    'Alcalde',
    'Alcaldesa',
    'Alemania',
    'Ambient',
    'Andorra',
    'Angola',
    'Anfitrión',
    'Anime',
    'Antigua y Barbuda',
    'Arabia Saudita',
    'Argelia',
    'Argentina',
    'Armenia',
    'Art pop',
    'Artes marciales mixtas (MMA)',
    'Artista',
    'Astronauta',
    'Atletismo',
    'Australia',
    'Austria',
    'Automovilismo',
    'Autor',
    'Azerbaiyán',
    'Bachata',
    'Bádminton',
    'Bahamas',
    'Bailarín',
    'Bailarina',
    'Baloncesto',
    'Balonmano',
    'Balonmano playa',
    'Banda',
    'Bandy',
    'Bangladés',
    'Barbados',
    'Baréin',
    'Béisbol',
    'Béisbol de campo',
    'Bélgica',
    'Belice',
    'Benín',
    'Biatlón',
    'Bielorrusia',
    'Billar',
    'Blues',
    'Blues rock',
    'Bobsleigh',
    'Bolero',
    'Bolivia',
    'Bolos',
    'Bosnia y Herzegovina',
    'Bossa nova',
    'Botsuana',
    'Boxeo',
    'Brasil',
    'Bridge',
    'Brunéi',
    'Bubblegum pop',
    'Buceo',
    'Bulgaria',
    'Bungee jumping',
    'Burkina Faso',
    'Burundi',
    'Bután',
    'Cabo Verde',
    'Camboya',
    'Camerún',
    'Canadá',
    'Candombe',
    'Canotaje',
    'Cantante',
    'Capoeira',
    'Carreras de autos',
    'Casual',
    'Catar',
    'Chad',
    'Chef',
    'Cheerleading',
    'Chile',
    'Chillwave',
    'China',
    'Chipre',
    'Ciencia Ficción',
    'Científico',
    'Ciclismo',
    'Cine',
    'Colombia',
    'Comediante',
    'Comoras',
    'Corea del Norte',
    'Corea del Sur',
    'Coros',
    'Costa de Marfil',
    'Costa Rica',
    'Country',
    'Creador de Contenido',
    'Cricket',
    'Croacia',
    'Croquet',
    'Crunk',
    'Cuba',
    'Cumbia',
    'Curling',
    'Dancehall',
    'Deportes',
    'Deportes de Pelota',
    'Dictador',
    'Dinamarca',
    'Diplomático',
    'Director',
    'Director de cine',
    'Disco',
    'Diseñador',
    'Diseñador de moda',
    'Diseñador de Vestuario',
    'DJ',
    'Dominica',
    'Dominó',
    'Drifting',
    'Drum and bass',
    'Dubstep',
    'Duque',
    'Duquesa',
    'E-sports',
    'Ecuador',
    'EDM (Electronic Dance Music)',
    'Egipto',
    'El Salvador',
    'Electropop',
    'Embajador',
    'Emiratos Árabes Unidos',
    'Emperador',
    'Empresario',
    'Enduro',
    'Equitación',
    'Eritrea',
    'Escalada',
    'Escalada en roca',
    'Escritor',
    'Esgrima',
    'Eslovaquia',
    'Eslovenia',
    'España',
    'Esquí acuático',
    'Esquí alpino',
    'Esquí de fondo',
    'Estados Unidos',
    'Estonia',
    'Estrategia',
    'Estudiante',
    'Etiopía',
    'Experimental',
    'Explorador',
    'Fantasía',
    'Filipinas',
    'Finlandia',
    'Filántropo',
    'Filósofo',
    'Fiyi',
    'Flamenco',
    'Floorball',
    'Folk',
    'Folk metal',
    'Fórmula 1',
    'Francia',
    'Frontón',
    'Fútbol',
    'Fútbol americano',
    'Fútbol sala',
    'Funk',
    'Funk carioca',
    'Gabón',
    'Gambia',
    'Gamer',
    'Gangsta rap',
    'Georgia',
    'Ghana',
    'Gimnasia',
    'Gimnasia artística',
    'Gimnasia rítmica',
    'Glam metal',
    'Glitch',
    'Go',
    'Gobernador',
    'Golf',
    'Gospel',
    'Granada',
    'Grecia',
    'Grunge',
    'Guatemala',
    'Guionista',
    'Guinea',
    'Guinea Ecuatorial',
    'Guinea-Bisáu',
    'Guyana',
    'Haití',
    'Halterofilia',
    'Hard rock',
    'Heavy metal',
    'Hípica',
    'Hip Hop',
    'Hip hop de la Costa Este',
    'Hip hop de la Costa Oeste',
    'Histórico',
    'Hockey sobre césped',
    'Hockey sobre hielo',
    'Honduras',
    'House',
    'Humorista',
    'Hungría',
    'India',
    'Indie rock',
    'Indonesia',
    'Industrial',
    'Influencer',
    'Inventor',
    'Investigador',
    'Irak',
    'Irán',
    'Irlanda',
    'Islandia',
    'Islas Marshall',
    'Islas Salomón',
    'Israel',
    'Italia',
    'J-Pop',
    'Jamaica',
    'Japón',
    'Jazz',
    'Jiu-jitsu',
    'Jordania',
    'Judo',
    'K-Pop',
    'Karate',
    'Karting',
    'Kayak',
    'Kazajistán',
    'Kendo',
    'Kenia',
    'Kickboxing',
    'Kin-Ball',
    'Kirguistán',
    'Kiribati',
    'Kuwait',
    'Lacrosse',
    'Laos',
    'Latin pop',
    'Lesoto',
    'Letonia',
    'Líbano',
    'Liberia',
    'Libia',
    'Líder de opinión',
    'Líder Mundial',
    'Liechtenstein',
    'Lituania',
    'Lucha libre',
    'Luge',
    'Luxemburgo',
    'Macedonia del Norte',
    'Madagascar',
    'Malasia',
    'Malaui',
    'Maldivas',
    'Malí',
    'Malta',
    'Manga',
    'Marcha atlética',
    'Marcha nórdica',
    'Marruecos',
    'Mauricio',
    'Mauritania',
    'Merengue',
    'México',
    'Micronesia',
    'Militar',
    'Modelo',
    'Moldavia',
    'Mónaco',
    'Monarca',
    'Mongolia',
    'Montenegro',
    'Motociclismo',
    'Motocross',
    'MotoGP',
    'Mozambique',
    'Mumble rap',
    'Música barroca',
    'Música Clásica',
    'Música de cámara',
    'Música para niños',
    'Música regional mexicana',
    'Música tradicional celta',
    'Música tradicional japonesa',
    'Músico',
    'Myanmar (Birmania)',
    'Namibia',
    'Natación',
    'Natación en aguas abiertas',
    'Natación sincronizada',
    'Nauru',
    'Nepal',
    'Netball',
    'New Age',
    'New Wave',
    'Nicaragua',
    'Níger',
    'Nigeria',
    'Noruega',
    'Novelista',
    'Nueva Zelanda',
    'Omán',
    'Ópera',
    'Pádel',
    'Padel surfing',
    'Países Bajos',
    'Pakistán',
    'Palaos',
    'Paleta frontón',
    'Panamá',
    'Papúa Nueva Guinea',
    'Paracaidismo',
    'Paraguay',
    'Parapente',
    'Parkour',
    'Patinaje',
    'Patinaje en línea',
    'Patinaje sobre hielo',
    'Pelota vasca',
    'Pentatlón moderno',
    'Periodista',
    'Perú',
    'Pilates',
    'Piragüismo',
    'Político',
    'Polonia',
    'Polo',
    'Polo a caballo',
    'Pop',
    'Pop punk',
    'Pop rock',
    'Portugal',
    'Post-punk',
    'Presentador',
    'Presidente',
    'Primer ministro',
    'Princesa',
    'Príncipe',
    'Productor',
    'Profesor',
    'Programador',
    'Punk rock',
    'R&B (Rhythm and Blues)',
    'Rafting',
    'Rally',
    'Rap',
    'Rap consciente',
    'Raquetbol',
    'Reggae',
    'Reggaeton',
    'Reina',
    'Reino Unido',
    'Remo',
    'Reportero',
    'República Centroafricana',
    'República Checa',
    'República del Congo',
    'República Democrática del Congo',
    'República Dominicana',
    'Rey',
    'Rock',
    'Rock alternativo',
    'Rock and Roll',
    'Rock progresivo',
    'Ruanda',
    'Rugby',
    'Rumania',
    'Rusia',
    'Salsa',
    'Salto de esquí',
    'Samoa',
    'Samba',
    'San Cristóbal y Nieves',
    'San Marino',
    'San Vicente y las Granadinas',
    'Sanda',
    'Santa Lucía',
    'Santo Tomé y Príncipe',
    'Senador',
    'Senegal',
    'Senderismo',
    'Serbia',
    'Serie de TV',
    'Seychelles',
    'Shoegaze',
    'Sierra Leona',
    'Singapur',
    'Siria',
    'Ska',
    'Skateboarding',
    'Skeleton',
    'Slackline',
    'Snowboarding',
    'Sófbol',
    'Somalia',
    'Soul',
    'Squash',
    'Sri Lanka',
    'Streamer',
    'Suazilandia',
    'Sudáfrica',
    'Sudán',
    'Sudán del Sur',
    'Suecia',
    'Sui géneris',
    'Suiza',
    'Sumo',
    'Superhéroe',
    'Surf',
    'Surinam',
    'Synth-pop',
    'Synthwave',
    'Taekwondo',
    'Tailandia',
    'Tango',
    'Tanzania',
    'Tayikistán',
    'Techno',
    'Tecnólogo',
    'Teen pop',
    'Tenis',
    'Tenis de mesa',
    'Terror',
    'Thrash metal',
    'TikToker',
    'Timor Oriental',
    'Tiro con arco',
    'Tiro deportivo',
    'Togo',
    'Tonga',
    'Trance',
    'Trap',
    'Triatlón',
    'Trinidad y Tobago',
    'Túnez',
    'Turkmenistán',
    'Turquía',
    'Tuvalu',
    'Ucrania',
    'Uganda',
    'Ultimate frisbee',
    'Uruguay',
    'Uzbekistán',
    'Vanuatu',
    'Vela',
    'Venezuela',
    'Vietnam',
    'Villano',
    'Voleibol',
    'Voleibol de playa',
    'Waterpolo',
    'Windsurf',
    'World music',
    'Wushu',
    'Yemen',
    'Yibuti',
    'Yoga',
    'Youtuber',
    'Zambia',
    'Zimbabue',
].sort((a, b) => a.localeCompare(b));
